name: Build Java Package

on:
  workflow_dispatch:
    inputs:
      skip-tests:
        type: boolean
        description: Skip Test Suite

jobs:
  build:

    runs-on: ubuntu-latest


    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn install -DskipTests=${{ inputs.skip-tests }}
    - name: Create Java package
      run: |
        cd application
        mvn package -DskipTests=true
    - name: Output artifact
      uses: actions/upload-artifact@v4
      with:
        name: Java Package
        path: application/target/hedgehog-*-jar-with-dependencies.jar
