name: Build Mac OSX (amd64) Executable

on:
  workflow_dispatch:
    inputs:
      skip-tests:
        type: boolean
        description: Skip Test Suite

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Setup GraalVM
      uses: ayltai/setup-graalvm@v1
      with:
        java-version: 17
        graalvm-version: 22.3.0
        native-image: true
    - name: Build with Maven
      run: mvn clean package -DskipTests=${{ inputs.skip-tests }}
    - name: Output artifact
      uses: actions/upload-artifact@v4
      with:
        name: OSX Native Binary
        path: native-image/target/hedgehog.bin
    - name: Run Binary
      run: native-image/target/hedgehog.bin
